version: '3'
services:
  web:
    image: nginx:latest
    container_name: nginx_welcome
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
